apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smsapplication
  template:
    metadata:
      labels:
        app: smsapplication
    spec:
      containers:
      - name: sms-container
        image: kruthim/smsapplication:v1
        ports:
        - containerPort: 8100
